routes/web.php
<?php


Route::namespace('Site')->group(function () {
  // Auth::routes();

    Route::get('/', ['as' => 'site.home', 'uses' => 'SiteController@index']);
    Route::get('/post/{slug}', ['as' => 'site.post.show', 'uses' => 'SiteController@showPost']);
    Route::get('/category/{slug}', ['as' => 'site.category.show', 'uses' => 'SiteController@showCategory']);

    Route::post('/comment/{id}', ['as' => 'site.comment.show', 'uses' => 'SiteController@showComment']);
    Route::post('/comment', ['as' => 'site.comment.store', 'uses' => 'SiteController@storeComment']);

    Route::get('/contacts', ['as' => 'site.contacts', 'uses' => 'SiteController@showContacts']);
    Route::get('/about_us', ['as' => 'site.aboutus', 'uses' => 'SiteController@showAboutUs']);
    // Show users profile - viewable by other users.
    Route::get('author/{username}', ['as'        => '{username}', 'uses'      => 'ProfilesController@show']);
});

Route::namespace('Admin')->group(function () {
    Route::prefix('admin')->group(function () {

        // Authentication for admin users
        Route::get('/login', ['as' => 'admin.login', 'uses' => 'Auth\LoginController@showLoginForm']);
        Route::post('/login', ['as' => 'admin.login.submit', 'uses' => 'Auth\LoginController@login']);
        Route::post('/logout', ['as' => 'admin.logout', 'uses' => 'Auth\LoginController@logout']);
        Route::post('/password/email', ['as' => 'admin.password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
        Route::get('/password/reset', ['as' => 'admin.password.request', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
        Route::post('/password/reset', ['as' => 'admin.password.reset.request', 'uses' => 'Auth\ResetPasswordController@reset']);
        Route::get('/password/reset/{token}', ['as' => 'admin.password.reset', 'uses' => 'Auth\ResetPasswordController@showResetForm']);

        // Main admin page
        Route::get('/', ['as' => 'admin.home', 'uses' => 'AdminController@index']);

        // Show users profile - viewable by other users.
        Route::get('profile/{username}', ['as'        => '{username}', 'uses'      => 'ProfilesController@show']);

        // User Profile and Account Routes
        Route::resource('profile', 'ProfilesController', [
                'name'  => [
                    'show' => 'admin.profile.show',
                    'edit',
                    'update',
                    'create',
                ],
            ]
        );
        Route::put('profile/{username}/updateUserAccount', [
            'as'        => '{username}',
            'uses'      => 'ProfilesController@updateUserAccount',
        ]);
        // Route::put('profile/{username}/updateUserPassword', [
        //     'as'        => '{username}',
        //     'uses'      => 'ProfilesController@updateUserPassword',
        // ]);
        // Route::delete('profile/{username}/deleteUserAccount', [
        //     'as'        => '{username}',
        //     'uses'      => 'ProfilesController@deleteUserAccount',
        // ]);
        //
        // // Route to show user avatar
        // Route::get('images/admins/profiles/{id}/avatar/{image}', [
        //     'uses'      => 'ProfilesController@userProfileAvatar',
        // ]);
        //
        // // Route to upload user avatar.
        // Route::post('avatar/upload', ['as' => 'avatar.upload', 'uses' => 'ProfilesController@upload']);

        // Permissions CRUD
        Route::resource('permissions', 'PermissionController', [
            'names' => [
                'index' => 'admin.permissions',
                'create' => 'admin.permission.create',
                'store' => 'admin.permission.store',
                'edit' => 'admin.permission.edit',
                'update' => 'admin.permission.update',
                'destroy' => 'admin.permission.destroy',
            ],
            'except' => ['show'],
        ]);
        Route::get('/permissions/delete/{id}', ['as' => 'admin.permission.delete', 'uses' => 'PermissionController@delete']);

        //Roles CRUD
        Route::resource('roles', 'RoleController', [
            'names' => [
                'index' => 'admin.roles',
                'show' => 'admin.role.show',
                'create' => 'admin.role.create',
                'store' => 'admin.role.store',
                'edit' => 'admin.role.edit',
                'update' => 'admin.role.update',
                'destroy' => 'admin.role.destroy',
            ],
        ]);
        Route::get('/roles/delete/{id}', ['as' => 'admin.role.delete', 'uses' => 'RoleController@delete']);

        // Admin users CRUD
        Route::resource('admins', 'AdminUserController', [
            'names' => [
                'index' => 'admin.admins',
                'show' => 'admin.admin.show',
                'create' => 'admin.admin.create',
                'store' => 'admin.admin.store',
                'edit' => 'admin.admin.edit',
                'update' => 'admin.admin.update',
                'destroy' => 'admin.admin.destroy',
            ],
        ]);
        Route::get('/admins/delete/{id}', ['as' => 'admin.admin.delete', 'uses' => 'AdminUserController@delete']);

        // Site users CRUD
        // Route::resource('users', 'SiteUserController', [
        //     'names' => [
        //         'index' => 'admin.users',
        //         'show' => 'admin.user.show',
        //         'create' => 'admin.user.create',
        //         'store' => 'admin.user.store',
        //         'edit' => 'admin.user.edit',
        //         'update' => 'admin.user.update',
        //         'destroy' => 'admin.user.destroy',
        //     ],
        // ]);
        // Route::get('/users/delete/{id}', ['as' => 'admin.user.delete', 'uses' => 'SiteUserController@delete']);

        // Posts CRUD
        Route::resource('posts', 'PostController', [
            'names' => [
                'index' => 'admin.posts',
                'show' => 'admin.post.show',
                'create' => 'admin.post.create',
                'store' => 'admin.post.store',
                'edit' => 'admin.post.edit',
                'update' => 'admin.post.update',
                'destroy' => 'admin.post.destroy',
            ],
        ]);
        Route::get('/posts/delete/{id}', ['as' => 'admin.post.delete', 'uses' => 'PostController@delete']);

        // Categories CRUD
        Route::resource('categories', 'CategoryController', [
            'names' => [
                'index' => 'admin.categories',
                'show' => 'admin.category.show',
                'create' => 'admin.category.create',
                'store' => 'admin.category.store',
                'edit' => 'admin.category.edit',
                'update' => 'admin.category.update',
                'destroy' => 'admin.category.destroy',
            ],
        ]);
        Route::get('/categories/delete/{id}', ['as' => 'admin.category.delete', 'uses' => 'CategoryController@delete']);

        // Comments CRUD
        Route::resource('comments', 'CommentController', [
            'names' => [
                'index' => 'admin.comments',
                'create' => 'admin.comment.create',
                'store' => 'admin.comment.store',
                'edit' => 'admin.comment.edit',
                'update' => 'admin.comment.update',
                'destroy' => 'admin.comment.destroy',
            ],
            'except' => ['show', 'create', 'store'],
        ]);
        Route::get('/comments/delete/{id}', ['as' => 'admin.comment.delete', 'uses' => 'CommentController@delete']);
    });
});

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Events\NewComment;

class Comment extends Model
{
    protected $fillable = [
        'comment', 'user_id', 'user_type', 'status'
    ];

    public function getCommentsList()
    {
        return $this->sort()->paginate(10);
    }

    public function getCommentById($id)
    {
        return $this->findOrFail($id);
    }

    public function updateComment($request, $id)
    {
        $comment = $this->getCommentById($id);

        $oldStatus = $comment->status;

        $comment->comment = $request->comment;
        $comment->status = $request->status;

        $comment->touch();
        $comment->save();
    }

    public function destroyComment($id)
    {
        $comment = $this->getCommentById($id);
        $comment->delete();
    }

    public function scopeSort($query)
    {
        $query->latest('id');
    }

    public function getCreatedAtAttribute($value)
    {
        return date('M j, Y | H:i:s', strtotime($value));
    }

    public function getUpdatedAtAttribute($value)
    {
        return date('M j, Y | H:i:s', strtotime($value));
    }

    public function post()
    {
        return $this->belongsTo('App\Models\Post');
    }

    public function user()
    {
        return $this->morphTo();
    }
}

app/Http/Controllers/Admin/CommentController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Models\Comment;

class CommentController extends \App\Http\Controllers\Controller
{
    private $commentModel;

    public function __construct(Comment $commentModel)
    {
        $this->middleware('admin');
        $this->middleware('permission:read-comments')->only(['index']);
        $this->middleware('permission:update-comments')->only(['edit', 'update']);
        $this->middleware('permission:delete-comments')->only(['delete', 'destroy']);

        $this->commentModel = $commentModel;
    }

    public function index()
    {
        $comments = $this->commentModel->getCommentsList();

        return view('admin.comment.all', [
            'comments' => $comments,
        ]);
    }

    public function edit($id)
    {
        $comment = $this->commentModel->getCommentById($id);

        return view('admin.comment.edit', [
            'comment' => $comment,
        ]);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'comment' => 'max:500',
            'status' => 'integer|max:1'
        ]);

        $this->commentModel->updateComment($request, $id);

        $request->session()->flash('success', __('admin/blog.alerts.comment_update_success'));

        return redirect()->route('admin.comments');
    }

    public function delete($id)
    {
        $comment = $this->commentModel->getCommentById($id);

        return view('admin.comment.delete', [
            'comment' => $comment,
        ]);
    }

    public function destroy(Request $request, $id)
    {
        $this->commentModel->destroyComment($id);

        $request->session()->flash('success', __('admin/blog.alerts.comment_delete_success'));

        return redirect()->to($request->redirect_to);
    }
}

resources/views/admin/comment/all.blade.php
@extends('layouts.admin')

@section('title')
    @lang('admin/blog.titles.comments')
@endsection


@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3 style="margin:0">التعليقات</h3>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>التعليق</th>
                                <th>الكاتب</th>
                                <th>المشاركة</th>
                                <th>الحالة</th>
                                <th style="min-width:210px">التاريخ</th>
                                <th style="min-width:100px"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($comments as $comment)
                                <tr>
                                    <td>{{ $comment->id }}</td>
                                    <td>{{ $comment->comment }}</td>
                                    <td>{{ $comment->user->name }}</td>
                                    <td>{{ $comment->post->title }}</td>
                                    <td>{!! $comment->status ? '<i class="fa fa-check text-success"></i>' : '<i class="fa fa-ban text-danger"></i>' !!}</td>
                                    <td>
                                        <i class="fa fa-plus"></i> {{ $comment->created_at }}<br>
                                        <i class="fa fa-refresh"></i> {{ $comment->updated_at }}<br>
                                    </td>
                                    <td class="text-right">
                                        <a href="{{ route('admin.comment.edit', ['id' => $comment->id]) }}" class="button is-wight is-small"><i class="fa fa-edit"></i></a>
                                        <a href="{{ route('admin.comment.delete', ['id' => $comment->id]) }}" class="button is-danger is-small"><i class="fa fa-trash"></i></a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>

            @if($comments->lastPage() > 1)
                <div class="panel panel-default">
                    <div class="panel-body text-center">
                        {{ $comments->links() }}
                    </div>
                </div>
            @endif

        </div>
    </div>
</div>
@endsection

resources/views/admin/comment/delete.blade.php
@extends('layouts.admin')

@section('title')
    حذف التعليق؟
@endsection


@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-12">

            <div class="panel panel-default">
                <div class="panel-body">
                        <h3 style="margin:0">حذف التعليق؟</h3>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6 col-md-offset-3">

                    <div class="panel panel-default">
                        <div class="panel-body">

                            <div class="well">
                                {{ $comment->comment }}
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <form action="{{ route('admin.comment.destroy', ['id' => $comment->id]) }}" method="POST">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}
                                        <input type="text" name="redirect_to" hidden value="{{ URL::previous() }}">
                                        <button type="submit" class="button is-fullwidth is-danger"><i class="fa fa-trash"></i>&nbsp; حذف</button>
                                    </form>
                                </div>
                                <div class="col-md-6">
                                    <a href="{{ URL::previous() }}" class="button is-fullwidth is-wight">إلغاء</a>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>
</div>

@endsection

resources/views/admin/comment/edit.blade.php
@extends('layouts.admin')

@section('title')
    تعديل التعليق
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3 style="margin:0">تعديل التعليق</h3>

                </div>
            </div>

            <form action="{{ route('admin.comment.update', ['id' => $comment->id]) }}" method="POST">

                {{ csrf_field() }}
                {{ method_field('PUT') }}
                <input type="text" name="redirect_to" value="{{ old('redirect_to', URL::previous()) }}" hidden>

                <div class="panel panel-default">
                    <div class="panel-body">

                        <dl class="dl-horizontal">
                            <dt>الكاتب</dt>
                            <dd>{{ $comment->user->name }}</dd>

                            <dt>المشاركة</dt>
                            <dd>{{ $comment->post->title }}</dd>
                        </dl>

                        <div class="form-group {{ $errors->has('comment') ? 'has-error' : '' }}">
                            <label for="comment">التعليق</label>
                            <textarea style="height:150px;" class="form-control" id="comment" name="comment">{{ old('comment', $comment->comment) }}</textarea>
                            @if ($errors->has("comment"))
                                <span class="help-block">
                                    <strong>{{ $errors->first("comment") }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group {{ $errors->has('status') ? 'has-error' : '' }}">
                            <label for="status">الحالة</label><br>
                            <div class="btn-group" data-toggle="buttons">
                                <label class="btn btn-default {{ old('status', $comment->status) ? 'active' : '' }}">
                                    <input value="1" name="status" type="radio" autocomplete="off" {{ old('status', $comment->status) ? 'checked' : '' }}> <i class="fa fa-check-square-o"></i> إظهار
                                </label>
                                <label class="btn btn-default {{ old('status', $comment->status) ? '' : 'active' }}">
                                    <input value="0" name="status" type="radio" autocomplete="off" {{ old('status', $comment->status) ? '' : 'checked' }}> <i class="fa fa-ban"></i> إخفاء
                                </label>
                            </div>
                            @if ($errors->has('status'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('status') }}</strong>
                                </span>
                            @endif
                        </div>

                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-body">

                        <div class="row">
                            <div class="col-md-6">
                                <button type="submit" class="button is-primary is-fullwidth"><i class="fa fa-save"></i>&nbsp; حفظ</button>
                            </div>
                            <div class="col-md-6">
                                <a href="{{ old('redirect_to', URL::previous()) }}" class="button is-wight is-fullwidth"><i class="fa fa-times"></i>&nbsp; إلغاء</a>
                            </div>
                        </div>

                    </div>
                </div>

            </form>

        </div>
    </div>
</div>

@endsection